export default function usage() {
	return [
		'CLI spell and grammar checker built on LanguageTool.',
		'',
		'Usage:',
		'  languagetool-node [options] [files...]',
		'',
		'Checks the given files (or text piped to STDIN) against an externally',
		'managed LanguageTool HTTP service and prints a report.',
		'',
		'Examples:',
		'  languagetool-node README.md CHANGELOG.md       check files',
		'  languagetool-node ~/project1/**/*.txt          check files via globs',
		'  echo "text to check" | languagetool-node       check text from STDIN',
		'',
		'Options:',
		'  -h, --help                  show this help and exit',
		'  -V, --version               print the CLI version and exit',
		'  -u, --url <url>             override the LanguageTool service URL for',
		'                              this invocation (takes precedence over config)',
		'',
		'Configuration:',
		'  Service URL and ignored words are read from ~/.languagetoolrc.js,',
		'  merged over the bundled default. The default service URL is',
		'  http://127.0.0.1:8081 — point it at your own LanguageTool instance.',
	].join('\n');
}
